import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import webpush from "web-push";

/**
 * The hub's VAPID material (PORCH-059, ac-1). The keypair is generated by
 * the hub's runtime setup at first run and held in hub server state —
 * `<home>/state/vapid-keys.json`, mode 0600 — never committed to the
 * repository, following the ops-token state pattern (PORCH-040). Every
 * generated push carries the same VAPID identity across restarts, so
 * browser subscriptions never churn per boot.
 */

export interface VapidMaterial {
  subject: string;
  publicKey: string;
  privateKey: string;
  createdAt: string;
}

/** VAPID subject: the protocol's contact claim; no phone-home ever rides it. */
const VAPID_SUBJECT = "mailto:owner@porchlight.hub";

/**
 * Load the stored VAPID material, or generate and persist it at first run.
 * Idempotent: every boot after the first reuses the same keypair. A corrupt
 * or unusable store regenerates (the browser-side subscriptions would then
 * be re-registered by their own 404/410 cleanup) with the failure logged.
 */
export function loadVapidKeys(homeRoot: string | null, log?: (line: string) => void): VapidMaterial | null {
  if (!homeRoot) return null;
  const file = join(homeRoot, "state", "vapid-keys.json");
  if (existsSync(file)) {
    try {
      const parsed = JSON.parse(readFileSync(file, "utf8")) as Partial<VapidMaterial>;
      if (typeof parsed.publicKey === "string" && typeof parsed.privateKey === "string") {
        return {
          subject: parsed.subject ?? VAPID_SUBJECT,
          publicKey: parsed.publicKey,
          privateKey: parsed.privateKey,
          createdAt: parsed.createdAt ?? new Date().toISOString(),
        };
      }
      log?.(JSON.stringify({ kind: "push", event: "vapid.keys.invalid", at: new Date().toISOString() }));
    } catch {
      log?.(JSON.stringify({ kind: "push", event: "vapid.keys.corrupt", at: new Date().toISOString() }));
    }
  }
  const created = webpush.generateVAPIDKeys();
  const material: VapidMaterial = { subject: VAPID_SUBJECT, ...created, createdAt: new Date().toISOString() };
  mkdirSync(dirname(file), { recursive: true });
  // Server state, never committed: owner-only file mode on the state file.
  writeFileSync(file, `${JSON.stringify(material, null, 2)}\n`, { mode: 0o600 });
  log?.(JSON.stringify({ kind: "push", event: "vapid.keys.generated", at: material.createdAt }));
  return material;
}